// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7eEr-DNMHhWd5Uat4NsS1OuoerdrtDw',
    appId: '1:347779789597:web:588cd103468026800167f4',
    messagingSenderId: '347779789597',
    projectId: 'cupcare-c23e2',
    authDomain: 'cupcare-c23e2.firebaseapp.com',
    storageBucket: 'cupcare-c23e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyxWlnnR2quuv8J_pno6mU6XycErLcoo',
    appId: '1:347779789597:android:2706455088fcfeba0167f4',
    messagingSenderId: '347779789597',
    projectId: 'cupcare-c23e2',
    storageBucket: 'cupcare-c23e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kDVwVOb9Bnm-6dcYECPJt5acGplKncI',
    appId: '1:347779789597:ios:d6312fb6752e0c2e0167f4',
    messagingSenderId: '347779789597',
    projectId: 'cupcare-c23e2',
    storageBucket: 'cupcare-c23e2.appspot.com',
    iosBundleId: 'com.example.cupcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_kDVwVOb9Bnm-6dcYECPJt5acGplKncI',
    appId: '1:347779789597:ios:662af12c714765c80167f4',
    messagingSenderId: '347779789597',
    projectId: 'cupcare-c23e2',
    storageBucket: 'cupcare-c23e2.appspot.com',
    iosBundleId: 'com.example.cupcare.RunnerTests',
  );
}
